# Inserts a blank line between shell prompts
add_newline = true

format = """
[┌╴\\(](bold #06CD94)[$username@$hostname](bold #06CD94)[\\)](bold #06CD94)\
| $all[└─](#06CD94) $character\
"""

[character]
success_symbol = "💲"
error_symbol = "✗"

[username]
style_user = 'blue bold'
style_root = 'red bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname](bold blue)'
trim_at = '.companyname.com'
disabled = false

# No need for env variables as starship provides a way to show your current distro
[os]
style = "bold green"
format = "on [$symbol$arch$name](style)"



